import 'dotenv/config';
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { spots } from './schema';

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error('DATABASE_URL required');
  process.exit(1);
}

const client = postgres(connectionString);
const db = drizzle(client);

const moroccoSpots = [
  {
    name: 'Anchor Point',
    slug: 'anchor-point',
    region: 'morocco' as const,
    latitude: 30.5266,
    longitude: -9.8641,
    orientation: 315,
    breakType: 'point' as const,
    idealSwellDir: 315,
    idealWindDir: 90,
    description:
      'World-class right-hand point break. Long walls on NW swell with light east winds.',
  },
  {
    name: 'Killer Point',
    slug: 'killer-point',
    region: 'morocco' as const,
    latitude: 30.5334,
    longitude: -9.8711,
    orientation: 300,
    breakType: 'point' as const,
    idealSwellDir: 300,
    idealWindDir: 90,
    description: 'Powerful right point break, holds big swell. Named for the urchins.',
  },
  {
    name: 'La Source',
    slug: 'la-source',
    region: 'morocco' as const,
    latitude: 30.5356,
    longitude: -9.8726,
    orientation: 290,
    breakType: 'point' as const,
    idealSwellDir: 300,
    idealWindDir: 90,
    description: 'Fast, hollow right off a rock shelf. Needs solid swell to work.',
  },
  {
    name: 'Mysteries',
    slug: 'mysteries',
    region: 'morocco' as const,
    latitude: 30.5375,
    longitude: -9.8733,
    orientation: 280,
    breakType: 'point' as const,
    idealSwellDir: 290,
    idealWindDir: 80,
    description: 'Long peeling right, more mellow than Anchor Point. Good for intermediates.',
  },
  {
    name: 'Hash Point',
    slug: 'hash-point',
    region: 'morocco' as const,
    latitude: 30.5414,
    longitude: -9.875,
    orientation: 270,
    breakType: 'point' as const,
    idealSwellDir: 280,
    idealWindDir: 90,
    description: 'Fun right-hander in the heart of Taghazout village.',
  },
  {
    name: 'Panoramas',
    slug: 'panoramas',
    region: 'morocco' as const,
    latitude: 30.5441,
    longitude: -9.8761,
    orientation: 270,
    breakType: 'beach' as const,
    idealSwellDir: 280,
    idealWindDir: 90,
    description: 'Beach break north of Taghazout, good for all levels.',
  },
  {
    name: 'Devils Rock',
    slug: 'devils-rock',
    region: 'morocco' as const,
    latitude: 30.5185,
    longitude: -9.858,
    orientation: 310,
    breakType: 'reef' as const,
    idealSwellDir: 310,
    idealWindDir: 80,
    description: 'Powerful reef break south of Anchor Point. Advanced only.',
  },
  {
    name: 'Banana Beach',
    slug: 'banana-beach',
    region: 'morocco' as const,
    latitude: 30.5095,
    longitude: -9.846,
    orientation: 270,
    breakType: 'beach' as const,
    idealSwellDir: 280,
    idealWindDir: 90,
    description: 'Sheltered beach break in Banana Village. Protected from wind.',
  },
  {
    name: 'Boilers',
    slug: 'boilers',
    region: 'morocco' as const,
    latitude: 30.5455,
    longitude: -9.877,
    orientation: 290,
    breakType: 'reef' as const,
    idealSwellDir: 300,
    idealWindDir: 90,
    description: 'Named for the shipwreck boiler on the reef. Short but intense right.',
  },
  {
    name: 'Dracula',
    slug: 'dracula',
    region: 'morocco' as const,
    latitude: 30.5,
    longitude: -9.838,
    orientation: 280,
    breakType: 'point' as const,
    idealSwellDir: 290,
    idealWindDir: 80,
    description: 'Remote right point south of Tamraght. Long paddle, uncrowded.',
  },
  {
    name: 'Imsouane Cathedral',
    slug: 'imsouane-cathedral',
    region: 'morocco' as const,
    latitude: 30.8423,
    longitude: -9.8261,
    orientation: 180,
    breakType: 'point' as const,
    idealSwellDir: 210,
    idealWindDir: 0,
    description:
      'Longest right-hand wave in Africa. Can ride for over a minute on big days.',
  },
  {
    name: 'Imsouane Bay',
    slug: 'imsouane-bay',
    region: 'morocco' as const,
    latitude: 30.8388,
    longitude: -9.8295,
    orientation: 200,
    breakType: 'beach' as const,
    idealSwellDir: 220,
    idealWindDir: 0,
    description: 'Mellow bay wave, perfect for longboarding and intermediates.',
  },
  {
    name: 'Tamri',
    slug: 'tamri',
    region: 'morocco' as const,
    latitude: 30.6914,
    longitude: -9.8506,
    orientation: 270,
    breakType: 'beach' as const,
    idealSwellDir: 280,
    idealWindDir: 90,
    description: 'Big open beach break near banana plantations. Powerful and uncrowded.',
  },
  {
    name: 'Anza',
    slug: 'anza',
    region: 'morocco' as const,
    latitude: 30.439,
    longitude: -9.663,
    orientation: 270,
    breakType: 'reef' as const,
    idealSwellDir: 280,
    idealWindDir: 90,
    description: 'Urban reef break in Agadir. Consistent and accessible.',
  },
  {
    name: 'Cro Cro',
    slug: 'cro-cro',
    region: 'morocco' as const,
    latitude: 30.5475,
    longitude: -9.878,
    orientation: 300,
    breakType: 'reef' as const,
    idealSwellDir: 310,
    idealWindDir: 90,
    description: 'Reef break just north of Taghazout. Short, punchy waves.',
  },
];

const baliSpots = [
  {
    name: 'Uluwatu',
    slug: 'uluwatu',
    region: 'bali' as const,
    latitude: -8.8154,
    longitude: 115.0852,
    orientation: 210,
    breakType: 'reef' as const,
    idealSwellDir: 210,
    idealWindDir: 45,
    description:
      'Iconic left-hand reef break beneath the cliff temple. Multiple takeoff zones.',
  },
  {
    name: 'Padang Padang',
    slug: 'padang-padang',
    region: 'bali' as const,
    latitude: -8.8124,
    longitude: 115.0976,
    orientation: 200,
    breakType: 'reef' as const,
    idealSwellDir: 200,
    idealWindDir: 45,
    description:
      'Barreling left over shallow reef. Needs solid south swell to break properly.',
  },
  {
    name: 'Bingin',
    slug: 'bingin',
    region: 'bali' as const,
    latitude: -8.8078,
    longitude: 115.1013,
    orientation: 200,
    breakType: 'reef' as const,
    idealSwellDir: 200,
    idealWindDir: 45,
    description: 'Short, hollow left. Crowded but perfectly shaped barrels.',
  },
  {
    name: 'Impossibles',
    slug: 'impossibles',
    region: 'bali' as const,
    latitude: -8.8052,
    longitude: 115.105,
    orientation: 210,
    breakType: 'reef' as const,
    idealSwellDir: 210,
    idealWindDir: 45,
    description: 'Three peaks that connect on big swells. Fast left walls.',
  },
  {
    name: 'Dreamland',
    slug: 'dreamland',
    region: 'bali' as const,
    latitude: -8.7998,
    longitude: 115.1093,
    orientation: 210,
    breakType: 'beach' as const,
    idealSwellDir: 210,
    idealWindDir: 45,
    description: 'Heavy beach break on the Bukit Peninsula. Powerful shore dump.',
  },
  {
    name: 'Balangan',
    slug: 'balangan',
    region: 'bali' as const,
    latitude: -8.7923,
    longitude: 115.1108,
    orientation: 210,
    breakType: 'reef' as const,
    idealSwellDir: 210,
    idealWindDir: 45,
    description: 'Fun left over reef with a chill vibe. Good for intermediates.',
  },
  {
    name: 'Canggu - Batu Bolong',
    slug: 'canggu-batu-bolong',
    region: 'bali' as const,
    latitude: -8.6534,
    longitude: 115.1311,
    orientation: 250,
    breakType: 'beach' as const,
    idealSwellDir: 240,
    idealWindDir: 90,
    description: 'Popular beach break in Canggu. Mellow and beginner-friendly.',
  },
  {
    name: 'Canggu - Echo Beach',
    slug: 'canggu-echo-beach',
    region: 'bali' as const,
    latitude: -8.6555,
    longitude: 115.1258,
    orientation: 250,
    breakType: 'reef' as const,
    idealSwellDir: 240,
    idealWindDir: 90,
    description: 'Punchy left-hand reef break. More power than Batu Bolong.',
  },
  {
    name: 'Keramas',
    slug: 'keramas',
    region: 'bali' as const,
    latitude: -8.5715,
    longitude: 115.4597,
    orientation: 140,
    breakType: 'reef' as const,
    idealSwellDir: 130,
    idealWindDir: 315,
    description:
      'World-class right on the east coast. Needs southeast swell. Night surfing available.',
  },
  {
    name: 'Medewi',
    slug: 'medewi',
    region: 'bali' as const,
    latitude: -8.3812,
    longitude: 114.8283,
    orientation: 240,
    breakType: 'point' as const,
    idealSwellDir: 230,
    idealWindDir: 90,
    description: "Long mellow left in West Bali. Bali's longest wave.",
  },
  {
    name: 'Nusa Dua',
    slug: 'nusa-dua',
    region: 'bali' as const,
    latitude: -8.7788,
    longitude: 115.2398,
    orientation: 140,
    breakType: 'reef' as const,
    idealSwellDir: 130,
    idealWindDir: 315,
    description: 'Right-hand reef break on the east side. Works in wet season.',
  },
  {
    name: 'Sanur Reef',
    slug: 'sanur-reef',
    region: 'bali' as const,
    latitude: -8.6819,
    longitude: 115.2635,
    orientation: 120,
    breakType: 'reef' as const,
    idealSwellDir: 120,
    idealWindDir: 300,
    description: 'Right-hander off Sanur. Mellow and good for longboarding.',
  },
  {
    name: 'Green Bowl',
    slug: 'green-bowl',
    region: 'bali' as const,
    latitude: -8.8373,
    longitude: 115.1843,
    orientation: 150,
    breakType: 'reef' as const,
    idealSwellDir: 150,
    idealWindDir: 315,
    description: 'Secluded beach, steep cliff descent. Left and right peaks.',
  },
  {
    name: 'Serangan',
    slug: 'serangan',
    region: 'bali' as const,
    latitude: -8.7282,
    longitude: 115.2383,
    orientation: 160,
    breakType: 'reef' as const,
    idealSwellDir: 150,
    idealWindDir: 315,
    description: 'Turtle Island reef break. Fun rights on east swell.',
  },
  {
    name: 'Pererenan',
    slug: 'pererenan',
    region: 'bali' as const,
    latitude: -8.6582,
    longitude: 115.1193,
    orientation: 250,
    breakType: 'beach' as const,
    idealSwellDir: 240,
    idealWindDir: 90,
    description: 'Beach break north of Canggu. Less crowded, more consistent.',
  },
];

async function seed() {
  console.log('Seeding spots...');

  const allSpots = [...moroccoSpots, ...baliSpots].map((s) => ({
    ...s,
    imageUrl: null,
    webcamUrls: [],
  }));

  await db.insert(spots).values(allSpots).onConflictDoNothing();

  console.log(`Seeded ${allSpots.length} spots (${moroccoSpots.length} Morocco, ${baliSpots.length} Bali)`);

  await client.end();
}

seed().catch((e) => {
  console.error('Seed failed:', e);
  process.exit(1);
});
